// Code generated by MockGen. DO NOT EDIT.

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"
	time "time"

	entity "github.com/kust1q/Zapp/main/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockauthService is a mock of authService interface.
type MockauthService struct {
	ctrl     *gomock.Controller
	recorder *MockauthServiceMockRecorder
	isgomock struct{} //nolint:unused
}

// MockauthServiceMockRecorder is the mock recorder for MockauthService.
type MockauthServiceMockRecorder struct {
	mock *MockauthService
}

// NewMockauthService creates a new mock instance.
func NewMockauthService(ctrl *gomock.Controller) *MockauthService {
	mock := &MockauthService{ctrl: ctrl}
	mock.recorder = &MockauthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthService) EXPECT() *MockauthServiceMockRecorder {
	return m.recorder
}

// ForgotPassword mocks base method.
func (m *MockauthService) ForgotPassword(ctx context.Context, req *entity.ForgotPassword) (*entity.Recovery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgotPassword", ctx, req)
	ret0, _ := ret[0].(*entity.Recovery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForgotPassword indicates an expected call of ForgotPassword.
func (mr *MockauthServiceMockRecorder) ForgotPassword(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotPassword", reflect.TypeOf((*MockauthService)(nil).ForgotPassword), ctx, req)
}

// GetRefreshTTL mocks base method.
func (m *MockauthService) GetRefreshTTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetRefreshTTL indicates an expected call of GetRefreshTTL.
func (mr *MockauthServiceMockRecorder) GetRefreshTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTTL", reflect.TypeOf((*MockauthService)(nil).GetRefreshTTL))
}

// RecoveryPassword mocks base method.
func (m *MockauthService) RecoveryPassword(ctx context.Context, req *entity.RecoveryPassword) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecoveryPassword", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecoveryPassword indicates an expected call of RecoveryPassword.
func (mr *MockauthServiceMockRecorder) RecoveryPassword(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecoveryPassword", reflect.TypeOf((*MockauthService)(nil).RecoveryPassword), ctx, req)
}

// Refresh mocks base method.
func (m *MockauthService) Refresh(ctx context.Context, req *entity.Refresh) (*entity.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, req)
	ret0, _ := ret[0].(*entity.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockauthServiceMockRecorder) Refresh(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockauthService)(nil).Refresh), ctx, req)
}

// SignIn mocks base method.
func (m *MockauthService) SignIn(ctx context.Context, req *entity.Credential) (*entity.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", ctx, req)
	ret0, _ := ret[0].(*entity.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignIn indicates an expected call of SignIn.
func (mr *MockauthServiceMockRecorder) SignIn(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockauthService)(nil).SignIn), ctx, req)
}

// SignOut mocks base method.
func (m *MockauthService) SignOut(ctx context.Context, req *entity.Refresh) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignOut", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignOut indicates an expected call of SignOut.
func (mr *MockauthServiceMockRecorder) SignOut(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignOut", reflect.TypeOf((*MockauthService)(nil).SignOut), ctx, req)
}

// SignUp mocks base method.
func (m *MockauthService) SignUp(ctx context.Context, req *entity.User) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, req)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUp indicates an expected call of SignUp.
func (mr *MockauthServiceMockRecorder) SignUp(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockauthService)(nil).SignUp), ctx, req)
}

// UpdatePassword mocks base method.
func (m *MockauthService) UpdatePassword(ctx context.Context, req *entity.UpdatePassword) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockauthServiceMockRecorder) UpdatePassword(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockauthService)(nil).UpdatePassword), ctx, req)
}

// VerifyAccessToken mocks base method.
func (m *MockauthService) VerifyAccessToken(tokenString string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAccessToken", tokenString)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAccessToken indicates an expected call of VerifyAccessToken.
func (mr *MockauthServiceMockRecorder) VerifyAccessToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAccessToken", reflect.TypeOf((*MockauthService)(nil).VerifyAccessToken), tokenString)
}

// MocktweetService is a mock of tweetService interface.
type MocktweetService struct {
	ctrl     *gomock.Controller
	recorder *MocktweetServiceMockRecorder
	isgomock struct{} //nolint:unused
}

// MocktweetServiceMockRecorder is the mock recorder for MocktweetService.
type MocktweetServiceMockRecorder struct {
	mock *MocktweetService
}

// NewMocktweetService creates a new mock instance.
func NewMocktweetService(ctrl *gomock.Controller) *MocktweetService {
	mock := &MocktweetService{ctrl: ctrl}
	mock.recorder = &MocktweetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktweetService) EXPECT() *MocktweetServiceMockRecorder {
	return m.recorder
}

// CreateRetweet mocks base method.
func (m *MocktweetService) CreateRetweet(ctx context.Context, userID, tweetID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRetweet", ctx, userID, tweetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRetweet indicates an expected call of CreateRetweet.
func (mr *MocktweetServiceMockRecorder) CreateRetweet(ctx, userID, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRetweet", reflect.TypeOf((*MocktweetService)(nil).CreateRetweet), ctx, userID, tweetID)
}

// CreateTweet mocks base method.
func (m *MocktweetService) CreateTweet(ctx context.Context, req *entity.Tweet) (*entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTweet", ctx, req)
	ret0, _ := ret[0].(*entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTweet indicates an expected call of CreateTweet.
func (mr *MocktweetServiceMockRecorder) CreateTweet(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTweet", reflect.TypeOf((*MocktweetService)(nil).CreateTweet), ctx, req)
}

// DeleteRetweet mocks base method.
func (m *MocktweetService) DeleteRetweet(ctx context.Context, userID, retweetID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRetweet", ctx, userID, retweetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRetweet indicates an expected call of DeleteRetweet.
func (mr *MocktweetServiceMockRecorder) DeleteRetweet(ctx, userID, retweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRetweet", reflect.TypeOf((*MocktweetService)(nil).DeleteRetweet), ctx, userID, retweetID)
}

// DeleteTweet mocks base method.
func (m *MocktweetService) DeleteTweet(ctx context.Context, userID, tweetID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTweet", ctx, userID, tweetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTweet indicates an expected call of DeleteTweet.
func (mr *MocktweetServiceMockRecorder) DeleteTweet(ctx, userID, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTweet", reflect.TypeOf((*MocktweetService)(nil).DeleteTweet), ctx, userID, tweetID)
}

// GetLikes mocks base method.
func (m *MocktweetService) GetLikes(ctx context.Context, tweetID, limit, offset int) ([]entity.SmallUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikes", ctx, tweetID, limit, offset)
	ret0, _ := ret[0].([]entity.SmallUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikes indicates an expected call of GetLikes.
func (mr *MocktweetServiceMockRecorder) GetLikes(ctx, tweetID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikes", reflect.TypeOf((*MocktweetService)(nil).GetLikes), ctx, tweetID, limit, offset)
}

// GetRepliesToTweet mocks base method.
func (m *MocktweetService) GetRepliesToTweet(ctx context.Context, tweetID, limit, offset int) ([]entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepliesToTweet", ctx, tweetID, limit, offset)
	ret0, _ := ret[0].([]entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepliesToTweet indicates an expected call of GetRepliesToTweet.
func (mr *MocktweetServiceMockRecorder) GetRepliesToTweet(ctx, tweetID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepliesToTweet", reflect.TypeOf((*MocktweetService)(nil).GetRepliesToTweet), ctx, tweetID, limit, offset)
}

// GetTweetById mocks base method.
func (m *MocktweetService) GetTweetById(ctx context.Context, tweetID int) (*entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTweetById", ctx, tweetID)
	ret0, _ := ret[0].(*entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTweetById indicates an expected call of GetTweetById.
func (mr *MocktweetServiceMockRecorder) GetTweetById(ctx, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTweetById", reflect.TypeOf((*MocktweetService)(nil).GetTweetById), ctx, tweetID)
}

// GetTweetsAndRetweetsByUsername mocks base method.
func (m *MocktweetService) GetTweetsAndRetweetsByUsername(ctx context.Context, username string, limit, offset int) ([]entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTweetsAndRetweetsByUsername", ctx, username, limit, offset)
	ret0, _ := ret[0].([]entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTweetsAndRetweetsByUsername indicates an expected call of GetTweetsAndRetweetsByUsername.
func (mr *MocktweetServiceMockRecorder) GetTweetsAndRetweetsByUsername(ctx, username, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTweetsAndRetweetsByUsername", reflect.TypeOf((*MocktweetService)(nil).GetTweetsAndRetweetsByUsername), ctx, username, limit, offset)
}

// LikeTweet mocks base method.
func (m *MocktweetService) LikeTweet(ctx context.Context, userID, tweetID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikeTweet", ctx, userID, tweetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LikeTweet indicates an expected call of LikeTweet.
func (mr *MocktweetServiceMockRecorder) LikeTweet(ctx, userID, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikeTweet", reflect.TypeOf((*MocktweetService)(nil).LikeTweet), ctx, userID, tweetID)
}

// UnlikeTweet mocks base method.
func (m *MocktweetService) UnlikeTweet(ctx context.Context, userID, tweetID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlikeTweet", ctx, userID, tweetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlikeTweet indicates an expected call of UnlikeTweet.
func (mr *MocktweetServiceMockRecorder) UnlikeTweet(ctx, userID, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlikeTweet", reflect.TypeOf((*MocktweetService)(nil).UnlikeTweet), ctx, userID, tweetID)
}

// UpdateTweet mocks base method.
func (m *MocktweetService) UpdateTweet(ctx context.Context, req *entity.Tweet) (*entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTweet", ctx, req)
	ret0, _ := ret[0].(*entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTweet indicates an expected call of UpdateTweet.
func (mr *MocktweetServiceMockRecorder) UpdateTweet(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTweet", reflect.TypeOf((*MocktweetService)(nil).UpdateTweet), ctx, req)
}

// MockuserService is a mock of userService interface.
type MockuserService struct {
	ctrl     *gomock.Controller
	recorder *MockuserServiceMockRecorder
	isgomock struct{} //nolint:unused
}

// MockuserServiceMockRecorder is the mock recorder for MockuserService.
type MockuserServiceMockRecorder struct {
	mock *MockuserService
}

// NewMockuserService creates a new mock instance.
func NewMockuserService(ctrl *gomock.Controller) *MockuserService {
	mock := &MockuserService{ctrl: ctrl}
	mock.recorder = &MockuserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserService) EXPECT() *MockuserServiceMockRecorder {
	return m.recorder
}

// DeleteUser mocks base method.
func (m *MockuserService) DeleteUser(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockuserServiceMockRecorder) DeleteUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockuserService)(nil).DeleteUser), ctx, userID)
}

// FollowToUser mocks base method.
func (m *MockuserService) FollowToUser(ctx context.Context, followerID, followingID int) (*entity.Follow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowToUser", ctx, followerID, followingID)
	ret0, _ := ret[0].(*entity.Follow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowToUser indicates an expected call of FollowToUser.
func (mr *MockuserServiceMockRecorder) FollowToUser(ctx, followerID, followingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowToUser", reflect.TypeOf((*MockuserService)(nil).FollowToUser), ctx, followerID, followingID)
}

// GetFollowers mocks base method.
func (m *MockuserService) GetFollowers(ctx context.Context, username string, limit, offset int) ([]entity.SmallUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowers", ctx, username, limit, offset)
	ret0, _ := ret[0].([]entity.SmallUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowers indicates an expected call of GetFollowers.
func (mr *MockuserServiceMockRecorder) GetFollowers(ctx, username, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowers", reflect.TypeOf((*MockuserService)(nil).GetFollowers), ctx, username, limit, offset)
}

// GetFollowings mocks base method.
func (m *MockuserService) GetFollowings(ctx context.Context, username string, limit, offset int) ([]entity.SmallUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowings", ctx, username, limit, offset)
	ret0, _ := ret[0].([]entity.SmallUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowings indicates an expected call of GetFollowings.
func (mr *MockuserServiceMockRecorder) GetFollowings(ctx, username, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowings", reflect.TypeOf((*MockuserService)(nil).GetFollowings), ctx, username, limit, offset)
}

// GetMe mocks base method.
func (m *MockuserService) GetMe(ctx context.Context, userID, limit, offset int) (*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMe", ctx, userID, limit, offset)
	ret0, _ := ret[0].(*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMe indicates an expected call of GetMe.
func (mr *MockuserServiceMockRecorder) GetMe(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMe", reflect.TypeOf((*MockuserService)(nil).GetMe), ctx, userID, limit, offset)
}

// GetUserProfile mocks base method.
func (m *MockuserService) GetUserProfile(ctx context.Context, username string, limit, offset int) (*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", ctx, username, limit, offset)
	ret0, _ := ret[0].(*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile.
func (mr *MockuserServiceMockRecorder) GetUserProfile(ctx, username, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockuserService)(nil).GetUserProfile), ctx, username, limit, offset)
}

// UnfollowUser mocks base method.
func (m *MockuserService) UnfollowUser(ctx context.Context, followerID, followingID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfollowUser", ctx, followerID, followingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnfollowUser indicates an expected call of UnfollowUser.
func (mr *MockuserServiceMockRecorder) UnfollowUser(ctx, followerID, followingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfollowUser", reflect.TypeOf((*MockuserService)(nil).UnfollowUser), ctx, followerID, followingID)
}

// Update mocks base method.
func (m *MockuserService) Update(ctx context.Context, req *entity.UpdateBio) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockuserServiceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockuserService)(nil).Update), ctx, req)
}

// MockclientSearchService is a mock of clientSearchService interface.
type MockclientSearchService struct {
	ctrl     *gomock.Controller
	recorder *MockclientSearchServiceMockRecorder
	isgomock struct{} //nolint:unused
}

// MockclientSearchServiceMockRecorder is the mock recorder for MockclientSearchService.
type MockclientSearchServiceMockRecorder struct {
	mock *MockclientSearchService
}

// NewMockclientSearchService creates a new mock instance.
func NewMockclientSearchService(ctrl *gomock.Controller) *MockclientSearchService {
	mock := &MockclientSearchService{ctrl: ctrl}
	mock.recorder = &MockclientSearchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockclientSearchService) EXPECT() *MockclientSearchServiceMockRecorder {
	return m.recorder
}

// SearchTweets mocks base method.
func (m *MockclientSearchService) SearchTweets(ctx context.Context, query string) ([]entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTweets", ctx, query)
	ret0, _ := ret[0].([]entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTweets indicates an expected call of SearchTweets.
func (mr *MockclientSearchServiceMockRecorder) SearchTweets(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTweets", reflect.TypeOf((*MockclientSearchService)(nil).SearchTweets), ctx, query)
}

// SearchUsers mocks base method.
func (m *MockclientSearchService) SearchUsers(ctx context.Context, query string) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsers", ctx, query)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MockclientSearchServiceMockRecorder) SearchUsers(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MockclientSearchService)(nil).SearchUsers), ctx, query)
}

// MockfeedService is a mock of feedService interface.
type MockfeedService struct {
	ctrl     *gomock.Controller
	recorder *MockfeedServiceMockRecorder
	isgomock struct{} //nolint:unused
}

// MockfeedServiceMockRecorder is the mock recorder for MockfeedService.
type MockfeedServiceMockRecorder struct {
	mock *MockfeedService
}

// NewMockfeedService creates a new mock instance.
func NewMockfeedService(ctrl *gomock.Controller) *MockfeedService {
	mock := &MockfeedService{ctrl: ctrl}
	mock.recorder = &MockfeedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfeedService) EXPECT() *MockfeedServiceMockRecorder {
	return m.recorder
}

// GetDeafultFeed mocks base method.
func (m *MockfeedService) GetDeafultFeed(ctx context.Context, limit, offset int) ([]entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeafultFeed", ctx, limit, offset)
	ret0, _ := ret[0].([]entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeafultFeed indicates an expected call of GetDeafultFeed.
func (mr *MockfeedServiceMockRecorder) GetDeafultFeed(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeafultFeed", reflect.TypeOf((*MockfeedService)(nil).GetDeafultFeed), ctx, limit, offset)
}

// GetUserFeedByUserId mocks base method.
func (m *MockfeedService) GetUserFeedByUserId(ctx context.Context, userID, limit, offset int) ([]entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFeedByUserId", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFeedByUserId indicates an expected call of GetUserFeedByUserId.
func (mr *MockfeedServiceMockRecorder) GetUserFeedByUserId(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFeedByUserId", reflect.TypeOf((*MockfeedService)(nil).GetUserFeedByUserId), ctx, userID, limit, offset)
}

// MockmediaService is a mock of mediaService interface.
type MockmediaService struct {
	ctrl     *gomock.Controller
	recorder *MockmediaServiceMockRecorder
	isgomock struct{} //nolint:unused
}

// MockmediaServiceMockRecorder is the mock recorder for MockmediaService.
type MockmediaServiceMockRecorder struct {
	mock *MockmediaService
}

// NewMockmediaService creates a new mock instance.
func NewMockmediaService(ctrl *gomock.Controller) *MockmediaService {
	mock := &MockmediaService{ctrl: ctrl}
	mock.recorder = &MockmediaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmediaService) EXPECT() *MockmediaServiceMockRecorder {
	return m.recorder
}

// DeleteTweetMedia mocks base method.
func (m *MockmediaService) DeleteTweetMedia(ctx context.Context, tweetID, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTweetMedia", ctx, tweetID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTweetMedia indicates an expected call of DeleteTweetMedia.
func (mr *MockmediaServiceMockRecorder) DeleteTweetMedia(ctx, tweetID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTweetMedia", reflect.TypeOf((*MockmediaService)(nil).DeleteTweetMedia), ctx, tweetID, userID)
}

// GetAvatarDataByUserID mocks base method.
func (m *MockmediaService) GetAvatarDataByUserID(ctx context.Context, userID int) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarDataByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarDataByUserID indicates an expected call of GetAvatarDataByUserID.
func (mr *MockmediaServiceMockRecorder) GetAvatarDataByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarDataByUserID", reflect.TypeOf((*MockmediaService)(nil).GetAvatarDataByUserID), ctx, userID)
}

// GetMediaDataByTweetID mocks base method.
func (m *MockmediaService) GetMediaDataByTweetID(ctx context.Context, tweetID int) (*entity.TweetMedia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaDataByTweetID", ctx, tweetID)
	ret0, _ := ret[0].(*entity.TweetMedia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaDataByTweetID indicates an expected call of GetMediaDataByTweetID.
func (mr *MockmediaServiceMockRecorder) GetMediaDataByTweetID(ctx, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaDataByTweetID", reflect.TypeOf((*MockmediaService)(nil).GetMediaDataByTweetID), ctx, tweetID)
}

// MockwebSocketService is a mock of webSocketService interface.
type MockwebSocketService struct {
	ctrl     *gomock.Controller
	recorder *MockwebSocketServiceMockRecorder
	isgomock struct{} //nolint:unused
}

// MockwebSocketServiceMockRecorder is the mock recorder for MockwebSocketService.
type MockwebSocketServiceMockRecorder struct {
	mock *MockwebSocketService
}

// NewMockwebSocketService creates a new mock instance.
func NewMockwebSocketService(ctrl *gomock.Controller) *MockwebSocketService {
	mock := &MockwebSocketService{ctrl: ctrl}
	mock.recorder = &MockwebSocketServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwebSocketService) EXPECT() *MockwebSocketServiceMockRecorder {
	return m.recorder
}

// HandleConnection mocks base method.
func (m *MockwebSocketService) HandleConnection(w http.ResponseWriter, r *http.Request, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleConnection", w, r, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleConnection indicates an expected call of HandleConnection.
func (mr *MockwebSocketServiceMockRecorder) HandleConnection(w, r, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleConnection", reflect.TypeOf((*MockwebSocketService)(nil).HandleConnection), w, r, userID)
}

// MocknotificationService is a mock of notificationService interface.
type MocknotificationService struct {
	ctrl     *gomock.Controller
	recorder *MocknotificationServiceMockRecorder
	isgomock struct{} //nolint:unused
}

// MocknotificationServiceMockRecorder is the mock recorder for MocknotificationService.
type MocknotificationServiceMockRecorder struct {
	mock *MocknotificationService
}

// NewMocknotificationService creates a new mock instance.
func NewMocknotificationService(ctrl *gomock.Controller) *MocknotificationService {
	mock := &MocknotificationService{ctrl: ctrl}
	mock.recorder = &MocknotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknotificationService) EXPECT() *MocknotificationServiceMockRecorder {
	return m.recorder
}

// NotifyFollow mocks base method.
func (m *MocknotificationService) NotifyFollow(ctx context.Context, followerID, followingID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyFollow", ctx, followerID, followingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyFollow indicates an expected call of NotifyFollow.
func (mr *MocknotificationServiceMockRecorder) NotifyFollow(ctx, followerID, followingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyFollow", reflect.TypeOf((*MocknotificationService)(nil).NotifyFollow), ctx, followerID, followingID)
}

// NotifyLike mocks base method.
func (m *MocknotificationService) NotifyLike(ctx context.Context, actorID, tweetID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyLike", ctx, actorID, tweetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyLike indicates an expected call of NotifyLike.
func (mr *MocknotificationServiceMockRecorder) NotifyLike(ctx, actorID, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyLike", reflect.TypeOf((*MocknotificationService)(nil).NotifyLike), ctx, actorID, tweetID)
}

// NotifyReply mocks base method.
func (m *MocknotificationService) NotifyReply(ctx context.Context, actorID, tweetID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyReply", ctx, actorID, tweetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyReply indicates an expected call of NotifyReply.
func (mr *MocknotificationServiceMockRecorder) NotifyReply(ctx, actorID, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyReply", reflect.TypeOf((*MocknotificationService)(nil).NotifyReply), ctx, actorID, tweetID)
}

// NotifyRetweet mocks base method.
func (m *MocknotificationService) NotifyRetweet(ctx context.Context, actorID, tweetID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyRetweet", ctx, actorID, tweetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyRetweet indicates an expected call of NotifyRetweet.
func (mr *MocknotificationServiceMockRecorder) NotifyRetweet(ctx, actorID, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyRetweet", reflect.TypeOf((*MocknotificationService)(nil).NotifyRetweet), ctx, actorID, tweetID)
}
