apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: zapp
spec:
  template:
    spec:
      initContainers:
      - name: wait-postgres
        image: postgres:15
        command: ['sh', '-c', 'until pg_isready -h postgres -p 5432; do echo waiting; sleep 2; done']
      containers:
      - name: migrate
        image: migrate/migrate:latest
        args:
          - "-path=/migrations"
          - "-database=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?sslmode=disable"
          - "up"
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_DB
        volumeMounts:
          - name: migrations
            mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: db-migrations
      restartPolicy: Never
  backoffLimit: 4
