// Code generated by MockGen. DO NOT EDIT.

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/kust1q/Zapp/main/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockdb is a mock of db interface.
type Mockdb struct {
	ctrl     *gomock.Controller
	recorder *MockdbMockRecorder
	isgomock struct{}
}

// MockdbMockRecorder is the mock recorder for Mockdb.
type MockdbMockRecorder struct {
	mock *Mockdb
}

// NewMockdb creates a new mock instance.
func NewMockdb(ctrl *gomock.Controller) *Mockdb {
	mock := &Mockdb{ctrl: ctrl}
	mock.recorder = &MockdbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdb) EXPECT() *MockdbMockRecorder {
	return m.recorder
}

// DeleteUser mocks base method.
func (m *Mockdb) DeleteUser(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockdbMockRecorder) DeleteUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*Mockdb)(nil).DeleteUser), ctx, userID)
}

// FollowToUser mocks base method.
func (m *Mockdb) FollowToUser(ctx context.Context, followerID, followingID int, createdAt time.Time) (*entity.Follow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowToUser", ctx, followerID, followingID, createdAt)
	ret0, _ := ret[0].(*entity.Follow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowToUser indicates an expected call of FollowToUser.
func (mr *MockdbMockRecorder) FollowToUser(ctx, followerID, followingID, createdAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowToUser", reflect.TypeOf((*Mockdb)(nil).FollowToUser), ctx, followerID, followingID, createdAt)
}

// GetCounts mocks base method.
func (m *Mockdb) GetCounts(ctx context.Context, tweetID int) (*entity.Counters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounts", ctx, tweetID)
	ret0, _ := ret[0].(*entity.Counters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounts indicates an expected call of GetCounts.
func (mr *MockdbMockRecorder) GetCounts(ctx, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounts", reflect.TypeOf((*Mockdb)(nil).GetCounts), ctx, tweetID)
}

// GetFollowersIds mocks base method.
func (m *Mockdb) GetFollowersIds(ctx context.Context, username string, limit, offset int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowersIds", ctx, username, limit, offset)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowersIds indicates an expected call of GetFollowersIds.
func (mr *MockdbMockRecorder) GetFollowersIds(ctx, username, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowersIds", reflect.TypeOf((*Mockdb)(nil).GetFollowersIds), ctx, username, limit, offset)
}

// GetFollowingsIds mocks base method.
func (m *Mockdb) GetFollowingsIds(ctx context.Context, username string, limit, offset int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowingsIds", ctx, username, limit, offset)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowingsIds indicates an expected call of GetFollowingsIds.
func (mr *MockdbMockRecorder) GetFollowingsIds(ctx, username, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowingsIds", reflect.TypeOf((*Mockdb)(nil).GetFollowingsIds), ctx, username, limit, offset)
}

// GetTweetsAndRetweetsByUsername mocks base method.
func (m *Mockdb) GetTweetsAndRetweetsByUsername(ctx context.Context, username string, limit, offset int) ([]entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTweetsAndRetweetsByUsername", ctx, username, limit, offset)
	ret0, _ := ret[0].([]entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTweetsAndRetweetsByUsername indicates an expected call of GetTweetsAndRetweetsByUsername.
func (mr *MockdbMockRecorder) GetTweetsAndRetweetsByUsername(ctx, username, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTweetsAndRetweetsByUsername", reflect.TypeOf((*Mockdb)(nil).GetTweetsAndRetweetsByUsername), ctx, username, limit, offset)
}

// GetUserByID mocks base method.
func (m *Mockdb) GetUserByID(ctx context.Context, userID int) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockdbMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*Mockdb)(nil).GetUserByID), ctx, userID)
}

// GetUserByUsername mocks base method.
func (m *Mockdb) GetUserByUsername(ctx context.Context, username string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockdbMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*Mockdb)(nil).GetUserByUsername), ctx, username)
}

// UnfollowUser mocks base method.
func (m *Mockdb) UnfollowUser(ctx context.Context, followerID, followingID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfollowUser", ctx, followerID, followingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnfollowUser indicates an expected call of UnfollowUser.
func (mr *MockdbMockRecorder) UnfollowUser(ctx, followerID, followingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfollowUser", reflect.TypeOf((*Mockdb)(nil).UnfollowUser), ctx, followerID, followingID)
}

// UpdateUserBio mocks base method.
func (m *Mockdb) UpdateUserBio(ctx context.Context, userID int, bio string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserBio", ctx, userID, bio)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserBio indicates an expected call of UpdateUserBio.
func (mr *MockdbMockRecorder) UpdateUserBio(ctx, userID, bio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserBio", reflect.TypeOf((*Mockdb)(nil).UpdateUserBio), ctx, userID, bio)
}

// MockmediaService is a mock of mediaService interface.
type MockmediaService struct {
	ctrl     *gomock.Controller
	recorder *MockmediaServiceMockRecorder
	isgomock struct{}
}

// MockmediaServiceMockRecorder is the mock recorder for MockmediaService.
type MockmediaServiceMockRecorder struct {
	mock *MockmediaService
}

// NewMockmediaService creates a new mock instance.
func NewMockmediaService(ctrl *gomock.Controller) *MockmediaService {
	mock := &MockmediaService{ctrl: ctrl}
	mock.recorder = &MockmediaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmediaService) EXPECT() *MockmediaServiceMockRecorder {
	return m.recorder
}

// DeleteAvatar mocks base method.
func (m *MockmediaService) DeleteAvatar(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatar", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvatar indicates an expected call of DeleteAvatar.
func (mr *MockmediaServiceMockRecorder) DeleteAvatar(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatar", reflect.TypeOf((*MockmediaService)(nil).DeleteAvatar), ctx, userID)
}

// DeleteMediasByUserID mocks base method.
func (m *MockmediaService) DeleteMediasByUserID(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMediasByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMediasByUserID indicates an expected call of DeleteMediasByUserID.
func (mr *MockmediaServiceMockRecorder) DeleteMediasByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMediasByUserID", reflect.TypeOf((*MockmediaService)(nil).DeleteMediasByUserID), ctx, userID)
}

// GetAvatarUrlByUserID mocks base method.
func (m *MockmediaService) GetAvatarUrlByUserID(ctx context.Context, userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarUrlByUserID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarUrlByUserID indicates an expected call of GetAvatarUrlByUserID.
func (mr *MockmediaServiceMockRecorder) GetAvatarUrlByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarUrlByUserID", reflect.TypeOf((*MockmediaService)(nil).GetAvatarUrlByUserID), ctx, userID)
}

// GetMediaUrlByTweetID mocks base method.
func (m *MockmediaService) GetMediaUrlByTweetID(ctx context.Context, tweetID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaUrlByTweetID", ctx, tweetID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaUrlByTweetID indicates an expected call of GetMediaUrlByTweetID.
func (mr *MockmediaServiceMockRecorder) GetMediaUrlByTweetID(ctx, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaUrlByTweetID", reflect.TypeOf((*MockmediaService)(nil).GetMediaUrlByTweetID), ctx, tweetID)
}

// MockeventProducer is a mock of eventProducer interface.
type MockeventProducer struct {
	ctrl     *gomock.Controller
	recorder *MockeventProducerMockRecorder
	isgomock struct{}
}

// MockeventProducerMockRecorder is the mock recorder for MockeventProducer.
type MockeventProducerMockRecorder struct {
	mock *MockeventProducer
}

// NewMockeventProducer creates a new mock instance.
func NewMockeventProducer(ctrl *gomock.Controller) *MockeventProducer {
	mock := &MockeventProducer{ctrl: ctrl}
	mock.recorder = &MockeventProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockeventProducer) EXPECT() *MockeventProducerMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockeventProducer) Publish(ctx context.Context, topic string, event any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, topic, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockeventProducerMockRecorder) Publish(ctx, topic, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockeventProducer)(nil).Publish), ctx, topic, event)
}
