app:
  port: "50052"

elastic:
  host: "elasticsearch"
  port: "9200"

grpc:
  search_port: "50052"

kafka:
  brokers: ["kafka:9092"]
  topics: ["tweet-events", "user-events"]
  consumer:
    group_id: "search-service"
