// Code generated by MockGen. DO NOT EDIT.

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/kust1q/Zapp/main/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockmediaService is a mock of mediaService interface.
type MockmediaService struct {
	ctrl     *gomock.Controller
	recorder *MockmediaServiceMockRecorder
	isgomock struct{} //nolint:unused
}

// MockmediaServiceMockRecorder is the mock recorder for MockmediaService.
type MockmediaServiceMockRecorder struct {
	mock *MockmediaService
}

// NewMockmediaService creates a new mock instance.
func NewMockmediaService(ctrl *gomock.Controller) *MockmediaService {
	mock := &MockmediaService{ctrl: ctrl}
	mock.recorder = &MockmediaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmediaService) EXPECT() *MockmediaServiceMockRecorder {
	return m.recorder
}

// GetAvatarUrlByUserID mocks base method.
func (m *MockmediaService) GetAvatarUrlByUserID(ctx context.Context, userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarUrlByUserID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarUrlByUserID indicates an expected call of GetAvatarUrlByUserID.
func (mr *MockmediaServiceMockRecorder) GetAvatarUrlByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarUrlByUserID", reflect.TypeOf((*MockmediaService)(nil).GetAvatarUrlByUserID), ctx, userID)
}

// GetMediaUrlByTweetID mocks base method.
func (m *MockmediaService) GetMediaUrlByTweetID(ctx context.Context, tweetID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaUrlByTweetID", ctx, tweetID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaUrlByTweetID indicates an expected call of GetMediaUrlByTweetID.
func (mr *MockmediaServiceMockRecorder) GetMediaUrlByTweetID(ctx, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaUrlByTweetID", reflect.TypeOf((*MockmediaService)(nil).GetMediaUrlByTweetID), ctx, tweetID)
}

// MocktweetService is a mock of tweetService interface.
type MocktweetService struct {
	ctrl     *gomock.Controller
	recorder *MocktweetServiceMockRecorder
	isgomock struct{} //nolint:unused
}

// MocktweetServiceMockRecorder is the mock recorder for MocktweetService.
type MocktweetServiceMockRecorder struct {
	mock *MocktweetService
}

// NewMocktweetService creates a new mock instance.
func NewMocktweetService(ctrl *gomock.Controller) *MocktweetService {
	mock := &MocktweetService{ctrl: ctrl}
	mock.recorder = &MocktweetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktweetService) EXPECT() *MocktweetServiceMockRecorder {
	return m.recorder
}

// BuildEntityTweetToResponse mocks base method.
func (m *MocktweetService) BuildEntityTweetToResponse(ctx context.Context, tweet *entity.Tweet) (*entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildEntityTweetToResponse", ctx, tweet)
	ret0, _ := ret[0].(*entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildEntityTweetToResponse indicates an expected call of BuildEntityTweetToResponse.
func (mr *MocktweetServiceMockRecorder) BuildEntityTweetToResponse(ctx, tweet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildEntityTweetToResponse", reflect.TypeOf((*MocktweetService)(nil).BuildEntityTweetToResponse), ctx, tweet)
}

// MocksearchStorage is a mock of searchStorage interface.
type MocksearchStorage struct {
	ctrl     *gomock.Controller
	recorder *MocksearchStorageMockRecorder
	isgomock struct{} //nolint:unused
}

// MocksearchStorageMockRecorder is the mock recorder for MocksearchStorage.
type MocksearchStorageMockRecorder struct {
	mock *MocksearchStorage
}

// NewMocksearchStorage creates a new mock instance.
func NewMocksearchStorage(ctrl *gomock.Controller) *MocksearchStorage {
	mock := &MocksearchStorage{ctrl: ctrl}
	mock.recorder = &MocksearchStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksearchStorage) EXPECT() *MocksearchStorageMockRecorder {
	return m.recorder
}

// GetTweetsByIDs mocks base method.
func (m *MocksearchStorage) GetTweetsByIDs(ctx context.Context, ids []int) ([]entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTweetsByIDs", ctx, ids)
	ret0, _ := ret[0].([]entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTweetsByIDs indicates an expected call of GetTweetsByIDs.
func (mr *MocksearchStorageMockRecorder) GetTweetsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTweetsByIDs", reflect.TypeOf((*MocksearchStorage)(nil).GetTweetsByIDs), ctx, ids)
}

// GetUsersByIDs mocks base method.
func (m *MocksearchStorage) GetUsersByIDs(ctx context.Context, ids []int) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByIDs", ctx, ids)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByIDs indicates an expected call of GetUsersByIDs.
func (mr *MocksearchStorageMockRecorder) GetUsersByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByIDs", reflect.TypeOf((*MocksearchStorage)(nil).GetUsersByIDs), ctx, ids)
}

// MocksearchProvider is a mock of searchProvider interface.
type MocksearchProvider struct {
	ctrl     *gomock.Controller
	recorder *MocksearchProviderMockRecorder
	isgomock struct{} //nolint:unused
}

// MocksearchProviderMockRecorder is the mock recorder for MocksearchProvider.
type MocksearchProviderMockRecorder struct {
	mock *MocksearchProvider
}

// NewMocksearchProvider creates a new mock instance.
func NewMocksearchProvider(ctrl *gomock.Controller) *MocksearchProvider {
	mock := &MocksearchProvider{ctrl: ctrl}
	mock.recorder = &MocksearchProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksearchProvider) EXPECT() *MocksearchProviderMockRecorder {
	return m.recorder
}

// SearchTweets mocks base method.
func (m *MocksearchProvider) SearchTweets(ctx context.Context, query string) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTweets", ctx, query)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTweets indicates an expected call of SearchTweets.
func (mr *MocksearchProviderMockRecorder) SearchTweets(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTweets", reflect.TypeOf((*MocksearchProvider)(nil).SearchTweets), ctx, query)
}

// SearchUsers mocks base method.
func (m *MocksearchProvider) SearchUsers(ctx context.Context, query string) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsers", ctx, query)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MocksearchProviderMockRecorder) SearchUsers(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MocksearchProvider)(nil).SearchUsers), ctx, query)
}
