// Code generated by MockGen. DO NOT EDIT.

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	io "io"
	reflect "reflect"

	entity "github.com/kust1q/Zapp/main/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockdb is a mock of db interface.
type Mockdb struct {
	ctrl     *gomock.Controller
	recorder *MockdbMockRecorder
	isgomock struct{}
}

// MockdbMockRecorder is the mock recorder for Mockdb.
type MockdbMockRecorder struct {
	mock *Mockdb
}

// NewMockdb creates a new mock instance.
func NewMockdb(ctrl *gomock.Controller) *Mockdb {
	mock := &Mockdb{ctrl: ctrl}
	mock.recorder = &MockdbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdb) EXPECT() *MockdbMockRecorder {
	return m.recorder
}

// DeleteAvatarByUserID mocks base method.
func (m *Mockdb) DeleteAvatarByUserID(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatarByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvatarByUserID indicates an expected call of DeleteAvatarByUserID.
func (mr *MockdbMockRecorder) DeleteAvatarByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatarByUserID", reflect.TypeOf((*Mockdb)(nil).DeleteAvatarByUserID), ctx, userID)
}

// DeleteMediaByTweetID mocks base method.
func (m *Mockdb) DeleteMediaByTweetID(ctx context.Context, tweetID, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMediaByTweetID", ctx, tweetID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMediaByTweetID indicates an expected call of DeleteMediaByTweetID.
func (mr *MockdbMockRecorder) DeleteMediaByTweetID(ctx, tweetID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMediaByTweetID", reflect.TypeOf((*Mockdb)(nil).DeleteMediaByTweetID), ctx, tweetID, userID)
}

// GetAvatarDataByUserID mocks base method.
func (m *Mockdb) GetAvatarDataByUserID(ctx context.Context, userID int) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarDataByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarDataByUserID indicates an expected call of GetAvatarDataByUserID.
func (mr *MockdbMockRecorder) GetAvatarDataByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarDataByUserID", reflect.TypeOf((*Mockdb)(nil).GetAvatarDataByUserID), ctx, userID)
}

// GetAvatarPathByUserID mocks base method.
func (m *Mockdb) GetAvatarPathByUserID(ctx context.Context, userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarPathByUserID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarPathByUserID indicates an expected call of GetAvatarPathByUserID.
func (mr *MockdbMockRecorder) GetAvatarPathByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarPathByUserID", reflect.TypeOf((*Mockdb)(nil).GetAvatarPathByUserID), ctx, userID)
}

// GetMediaDataByTweetID mocks base method.
func (m *Mockdb) GetMediaDataByTweetID(ctx context.Context, tweetID int) (*entity.TweetMedia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaDataByTweetID", ctx, tweetID)
	ret0, _ := ret[0].(*entity.TweetMedia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaDataByTweetID indicates an expected call of GetMediaDataByTweetID.
func (mr *MockdbMockRecorder) GetMediaDataByTweetID(ctx, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaDataByTweetID", reflect.TypeOf((*Mockdb)(nil).GetMediaDataByTweetID), ctx, tweetID)
}

// GetMediaPathByTweetID mocks base method.
func (m *Mockdb) GetMediaPathByTweetID(ctx context.Context, tweetID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaPathByTweetID", ctx, tweetID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaPathByTweetID indicates an expected call of GetMediaPathByTweetID.
func (mr *MockdbMockRecorder) GetMediaPathByTweetID(ctx, tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaPathByTweetID", reflect.TypeOf((*Mockdb)(nil).GetMediaPathByTweetID), ctx, tweetID)
}

// GetMediaUrlsByUserID mocks base method.
func (m *Mockdb) GetMediaUrlsByUserID(ctx context.Context, userID int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaUrlsByUserID", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaUrlsByUserID indicates an expected call of GetMediaUrlsByUserID.
func (mr *MockdbMockRecorder) GetMediaUrlsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaUrlsByUserID", reflect.TypeOf((*Mockdb)(nil).GetMediaUrlsByUserID), ctx, userID)
}

// UploadAvatarTx mocks base method.
func (m *Mockdb) UploadAvatarTx(ctx context.Context, tx *sql.Tx, avatar *entity.Avatar) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatarTx", ctx, tx, avatar)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatarTx indicates an expected call of UploadAvatarTx.
func (mr *MockdbMockRecorder) UploadAvatarTx(ctx, tx, avatar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatarTx", reflect.TypeOf((*Mockdb)(nil).UploadAvatarTx), ctx, tx, avatar)
}

// UpsertByTweetIdTx mocks base method.
func (m *Mockdb) UpsertByTweetIdTx(ctx context.Context, tx *sql.Tx, media *entity.TweetMedia) (*entity.TweetMedia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertByTweetIdTx", ctx, tx, media)
	ret0, _ := ret[0].(*entity.TweetMedia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertByTweetIdTx indicates an expected call of UpsertByTweetIdTx.
func (mr *MockdbMockRecorder) UpsertByTweetIdTx(ctx, tx, media any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertByTweetIdTx", reflect.TypeOf((*Mockdb)(nil).UpsertByTweetIdTx), ctx, tx, media)
}

// MockobjectStorage is a mock of objectStorage interface.
type MockobjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockobjectStorageMockRecorder
	isgomock struct{}
}

// MockobjectStorageMockRecorder is the mock recorder for MockobjectStorage.
type MockobjectStorageMockRecorder struct {
	mock *MockobjectStorage
}

// NewMockobjectStorage creates a new mock instance.
func NewMockobjectStorage(ctrl *gomock.Controller) *MockobjectStorage {
	mock := &MockobjectStorage{ctrl: ctrl}
	mock.recorder = &MockobjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockobjectStorage) EXPECT() *MockobjectStorageMockRecorder {
	return m.recorder
}

// GetPresignedURL mocks base method.
func (m *MockobjectStorage) GetPresignedURL(ctx context.Context, objectPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresignedURL", ctx, objectPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresignedURL indicates an expected call of GetPresignedURL.
func (mr *MockobjectStorageMockRecorder) GetPresignedURL(ctx, objectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresignedURL", reflect.TypeOf((*MockobjectStorage)(nil).GetPresignedURL), ctx, objectPath)
}

// Remove mocks base method.
func (m *MockobjectStorage) Remove(ctx context.Context, objectPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, objectPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockobjectStorageMockRecorder) Remove(ctx, objectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockobjectStorage)(nil).Remove), ctx, objectPath)
}

// Upload mocks base method.
func (m *MockobjectStorage) Upload(ctx context.Context, file io.Reader, mediaType entity.MediaType, filename string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, file, mediaType, filename)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Upload indicates an expected call of Upload.
func (mr *MockobjectStorageMockRecorder) Upload(ctx, file, mediaType, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockobjectStorage)(nil).Upload), ctx, file, mediaType, filename)
}
