apiVersion: v1
kind: ConfigMap
metadata:
  name: main-config
  namespace: zapp
data:
  config.yml: |
    app:
      port: 8080
    db:
      host: postgres
      port: "5432"
      sslmode: disable
    minio:
      endpoint: minio
      port: "9000"
      bucketname: zapp-media
      sslmode: false
      ttl: 24h
    redis:
      host: redis
      port: "6379"
      db: 0
    cache:
      default_ttl: 10m
      counters_ttl: 1m
    tokens:
      access_ttl: 15m
      refresh_ttl: 7d
      recovery_ttl: 1h
    grpc:
      host: 0.0.0.0
      integration_port: "50051"
      search_port: "50052"
    kafka:
      brokers:
        - "kafka-headless.zapp.svc.cluster.local:9092"
      topics:
        - "tweet-events"
        - "user-events"
      producer:
        max_retries: 3
      consumer:
        group_id: "main-service"
    elastic:
      host: elasticsearch
      port: "9200"
