// Code generated by MockGen. DO NOT EDIT.

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/kust1q/Zapp/main/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockdb is a mock of db interface.
type Mockdb struct {
	ctrl     *gomock.Controller
	recorder *MockdbMockRecorder
	isgomock struct{}
}

// MockdbMockRecorder is the mock recorder for Mockdb.
type MockdbMockRecorder struct {
	mock *Mockdb
}

// NewMockdb creates a new mock instance.
func NewMockdb(ctrl *gomock.Controller) *Mockdb {
	mock := &Mockdb{ctrl: ctrl}
	mock.recorder = &MockdbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdb) EXPECT() *MockdbMockRecorder {
	return m.recorder
}

// GetAllTweets mocks base method.
func (m *Mockdb) GetAllTweets(ctx context.Context, limit, offset int) ([]entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTweets", ctx, limit, offset)
	ret0, _ := ret[0].([]entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTweets indicates an expected call of GetAllTweets.
func (mr *MockdbMockRecorder) GetAllTweets(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTweets", reflect.TypeOf((*Mockdb)(nil).GetAllTweets), ctx, limit, offset)
}

// GetFeedByAuthorsIds mocks base method.
func (m *Mockdb) GetFeedByAuthorsIds(ctx context.Context, userIDs []int, limit, offset int) ([]entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedByAuthorsIds", ctx, userIDs, limit, offset)
	ret0, _ := ret[0].([]entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedByAuthorsIds indicates an expected call of GetFeedByAuthorsIds.
func (mr *MockdbMockRecorder) GetFeedByAuthorsIds(ctx, userIDs, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedByAuthorsIds", reflect.TypeOf((*Mockdb)(nil).GetFeedByAuthorsIds), ctx, userIDs, limit, offset)
}

// GetFollowingsIds mocks base method.
func (m *Mockdb) GetFollowingsIds(ctx context.Context, username string, limit, offset int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowingsIds", ctx, username, limit, offset)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowingsIds indicates an expected call of GetFollowingsIds.
func (mr *MockdbMockRecorder) GetFollowingsIds(ctx, username, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowingsIds", reflect.TypeOf((*Mockdb)(nil).GetFollowingsIds), ctx, username, limit, offset)
}

// GetUserByID mocks base method.
func (m *Mockdb) GetUserByID(ctx context.Context, userID int) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockdbMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*Mockdb)(nil).GetUserByID), ctx, userID)
}

// MocktweetService is a mock of tweetService interface.
type MocktweetService struct {
	ctrl     *gomock.Controller
	recorder *MocktweetServiceMockRecorder
	isgomock struct{}
}

// MocktweetServiceMockRecorder is the mock recorder for MocktweetService.
type MocktweetServiceMockRecorder struct {
	mock *MocktweetService
}

// NewMocktweetService creates a new mock instance.
func NewMocktweetService(ctrl *gomock.Controller) *MocktweetService {
	mock := &MocktweetService{ctrl: ctrl}
	mock.recorder = &MocktweetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktweetService) EXPECT() *MocktweetServiceMockRecorder {
	return m.recorder
}

// BuildEntityTweetToResponse mocks base method.
func (m *MocktweetService) BuildEntityTweetToResponse(ctx context.Context, tweet *entity.Tweet) (*entity.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildEntityTweetToResponse", ctx, tweet)
	ret0, _ := ret[0].(*entity.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildEntityTweetToResponse indicates an expected call of BuildEntityTweetToResponse.
func (mr *MocktweetServiceMockRecorder) BuildEntityTweetToResponse(ctx, tweet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildEntityTweetToResponse", reflect.TypeOf((*MocktweetService)(nil).BuildEntityTweetToResponse), ctx, tweet)
}
