apiVersion: apps/v1
kind: Deployment
metadata:
  name: zapp-search
  namespace: zapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zapp-search
  template:
    metadata:
      labels:
        app: zapp-search
    spec:
      containers:
      - name: search
        image: zapp-search:latest
        ports:
          - containerPort: 50052
            name: grpc
        env:
          - name: ELASTIC_HOST
            value: "elasticsearch"
          - name: ELASTIC_PORT
            value: "9200"
          - name: KAFKA_BROKERS
            value: "kafka-headless.zapp.svc.cluster.local:9092"
          - name: KAFKA_TOPICS
            value: "tweet-events,user-events"
          - name: KAFKA_CONSUMER_GROUP_ID
            value: "search-service"
        volumeMounts:
          - name: config-volume
            mountPath: /app/configs
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: search-config
